data_path: 'input.txt'
checkpoint_path: 'models/checkpoint.pt'

batch_size: 4
n_emb: 16 
block_size: 8
num_heads: 4 
n_layer: 4
dropout: 0.2

seed: 1337
eval_iters: 500
max_steps: 5000
learning_rate: !!float 3e-4