data_path: 'input.txt'
checkpoint_path: 'models/checkpoint.pt'

batch_size: 64
n_emb: 384
block_size: 256
num_heads: 6 
n_layer: 6
dropout: 0.2

seed: 1337
eval_iters: 500
max_steps: 5000
learning_rate: !!float 3e-4